name: fm4g

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - numpy=1.26.4
  - libblas=*=*mkl
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  # StructuralGeo
  - tqdm
  - scipy
  - pyvista
  - jupyter
  - pyvistaqt
  - trame-vtk
  - trame
  - trame-vuetify
  - pydtmc
  - pip:
    - monai
    - nibabel==3.1.1
    - einops==0.4.1
    - itk
